# Generated by Django 4.0.5 on 2022-06-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mentor',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=70)),
                ('batch', models.IntegerField()),
                ('placed', models.CharField(max_length=70)),
                ('about', models.TextField()),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
